import jsPDF from 'jspdf';
import type { CareerAssets } from './gemini';

// ─── Color Palette (brand-aligned) ─────────────────────────────────────────
const VIOLET: [number, number, number] = [124, 58, 237];
const VIOLET_LIGHT: [number, number, number] = [167, 120, 247];
const BODY: [number, number, number] = [30, 30, 48];
const MUTED: [number, number, number] = [100, 116, 139];
const FOOTER_CLR: [number, number, number] = [148, 163, 184];
const WHITE: [number, number, number] = [255, 255, 255];
const SKILLS_BG: [number, number, number] = [245, 242, 255];
const TIP_BG: [number, number, number] = [245, 242, 255];
const CODE_BG: [number, number, number] = [241, 245, 249];
const BORDER_CLR: [number, number, number] = [226, 232, 240];
const ERROR_CLR: [number, number, number] = [220, 38, 38];
const SUCCESS_CLR: [number, number, number] = [34, 197, 94];

// ─── Layout Constants ───────────────────────────────────────────────────────
const MARGIN = 20;
const LINE_H = 5.6;
const PARA_GAP = 4;
const SECTION_GAP = 7;
const BULLET_INDENT = 6;
const BULLET_HANG = 3;
const FOOTER_HEIGHT = 16;

// ─── Helpers ────────────────────────────────────────────────────────────────

function safeName(name: string): string {
  return name.replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');
}

function pageWidth(doc: jsPDF): number {
  return doc.internal.pageSize.getWidth();
}

function pageHeight(doc: jsPDF): number {
  return doc.internal.pageSize.getHeight();
}

function contentWidth(doc: jsPDF): number {
  return pageWidth(doc) - MARGIN * 2;
}

function maxY(doc: jsPDF): number {
  return pageHeight(doc) - MARGIN - FOOTER_HEIGHT;
}

/** Set PDF metadata for searchability and accessibility. */
function setPDFMetadata(doc: jsPDF, title: string, candidateName: string, keywords: string[] = []): void {
  doc.setProperties({
    title,
    author: candidateName,
    subject: `VoiceCV - ${title}`,
    keywords: ['VoiceCV', 'resume', 'career', ...keywords].join(', '),
    creator: 'VoiceCV (voicecv.app)',
  });
}

/** Strip markdown formatting to get visible character count. */
function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/`(.+?)`/g, '$1')
    .replace(/^#+\s*/gm, '')
    .replace(/^[-*•]\s/gm, '')
    .replace(/^\d+\.\s/gm, '')
    .trim();
}

/** Ensure space for `needed` mm; add page if necessary. */
function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > maxY(doc)) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

/** Stamp branded footer with page numbers on every page. */
function stampFooters(doc: jsPDF): void {
  const total = doc.getNumberOfPages();
  const pw = pageWidth(doc);
  const ph = pageHeight(doc);

  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...FOOTER_CLR);

    const left = 'Generated by VoiceCV \u2022 voicecv.app';
    const right = `Page ${i} of ${total}`;

    doc.text(left, MARGIN, ph - 8);
    doc.text(right, pw - MARGIN - doc.getTextWidth(right), ph - 8);

    // Two-tone footer separator
    const midX = MARGIN + (pw - MARGIN * 2) * 0.35;
    doc.setDrawColor(...VIOLET_LIGHT);
    doc.setLineWidth(0.15);
    doc.line(MARGIN, ph - 12, midX, ph - 12);
    doc.setDrawColor(...BORDER_CLR);
    doc.setLineWidth(0.1);
    doc.line(midX, ph - 12, pw - MARGIN, ph - 12);
  }
}

// ─── Markdown-aware text rendering ──────────────────────────────────────────

interface TextSegment {
  text: string;
  bold: boolean;
  italic: boolean;
  code: boolean;
}

/** Parse markdown bold (**text**), italic (*text*), and inline code (`text`). */
function parseMarkdown(line: string): TextSegment[] {
  const segments: TextSegment[] = [];
  // Match bold, italic, and inline code in order of precedence
  const regex = /(\*\*(.+?)\*\*)|(\*(.+?)\*)|(`(.+?)`)/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(line)) !== null) {
    if (match.index > lastIndex) {
      segments.push({ text: line.slice(lastIndex, match.index), bold: false, italic: false, code: false });
    }
    if (match[1]) {
      // Bold: **text**
      segments.push({ text: match[2], bold: true, italic: false, code: false });
    } else if (match[3]) {
      // Italic: *text*
      segments.push({ text: match[4], bold: false, italic: true, code: false });
    } else if (match[5]) {
      // Inline code: `text`
      segments.push({ text: match[6], bold: false, italic: false, code: true });
    }
    lastIndex = regex.lastIndex;
  }

  if (lastIndex < line.length) {
    segments.push({ text: line.slice(lastIndex), bold: false, italic: false, code: false });
  }

  return segments.length ? segments : [{ text: line, bold: false, italic: false, code: false }];
}

/**
 * Render a line with bold/italic/code segments at (x, y). Returns the new x position.
 */
function renderMarkdownSegments(doc: jsPDF, segments: TextSegment[], x: number, y: number, fontSize: number): void {
  let cx = x;
  for (const seg of segments) {
    if (seg.code) {
      doc.setFont('courier', 'normal');
      doc.setFontSize(fontSize - 0.5);
      doc.setTextColor(...MUTED);
      // Draw subtle code background
      const tw = doc.getTextWidth(seg.text);
      doc.setFillColor(...CODE_BG);
      doc.roundedRect(cx - 0.5, y - 3.2, tw + 1, 4, 0.5, 0.5, 'F');
      doc.text(seg.text, cx, y);
      cx += tw;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(fontSize);
      doc.setTextColor(...BODY);
    } else {
      const style = seg.bold ? 'bold' : 'normal';
      doc.setFont('helvetica', style);
      doc.setFontSize(fontSize);
      doc.setTextColor(...BODY);
      doc.text(seg.text, cx, y);
      cx += doc.getTextWidth(seg.text);
    }
  }
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fontSize);
}

/**
 * Word-wrap a line that may contain **bold**, *italic*, or `code` markdown,
 * rendering each wrapped visual line with correct styling.
 * Returns new y after rendering.
 */
function renderWrappedBoldLine(
  doc: jsPDF,
  rawLine: string,
  x: number,
  y: number,
  maxWidth: number,
  fontSize: number,
  lineH: number = LINE_H,
  hangIndent: number = 0,
): number {
  doc.setFontSize(fontSize);

  const segments = parseMarkdown(rawLine);

  // Build a flat list of "word chunks" with their style state
  interface WordChunk { word: string; bold: boolean; italic: boolean; code: boolean }
  const words: WordChunk[] = [];
  for (const seg of segments) {
    const parts = seg.text.split(/(\s+)/);
    for (const part of parts) {
      if (part.length > 0) {
        words.push({ word: part, bold: seg.bold, italic: seg.italic, code: seg.code });
      }
    }
  }

  // Now lay out words line by line
  let lineWords: WordChunk[] = [];
  let lineWidth = 0;
  let isFirstLine = true;

  const flushLine = (currentY: number): number => {
    if (lineWords.length === 0) return currentY;
    const xOffset = isFirstLine ? x : x + hangIndent;
    let cx = xOffset;
    for (const w of lineWords) {
      if (w.code) {
        doc.setFont('courier', 'normal');
        doc.setFontSize(fontSize - 0.5);
        doc.setTextColor(...MUTED);
        const tw = doc.getTextWidth(w.word);
        doc.setFillColor(...CODE_BG);
        doc.roundedRect(cx - 0.5, currentY - 3.2, tw + 1, 4, 0.5, 0.5, 'F');
        doc.text(w.word, cx, currentY);
        cx += tw;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(fontSize);
        doc.setTextColor(...BODY);
      } else {
        doc.setFont('helvetica', w.bold ? 'bold' : 'normal');
        doc.setFontSize(fontSize);
        doc.text(w.word, cx, currentY);
        cx += doc.getTextWidth(w.word);
      }
    }
    isFirstLine = false;
    lineWords = [];
    lineWidth = 0;
    return currentY + lineH;
  };

  for (const chunk of words) {
    if (chunk.code) {
      doc.setFont('courier', 'normal');
      doc.setFontSize(fontSize - 0.5);
    } else {
      doc.setFont('helvetica', chunk.bold ? 'bold' : 'normal');
      doc.setFontSize(fontSize);
    }
    const chunkW = doc.getTextWidth(chunk.word);
    const currentMax = isFirstLine ? maxWidth : maxWidth - hangIndent;

    if (lineWidth + chunkW > currentMax && lineWords.length > 0) {
      y = ensureSpace(doc, y, lineH);
      y = flushLine(y);
    }
    lineWords.push(chunk);
    lineWidth += chunkW;
  }

  if (lineWords.length > 0) {
    y = ensureSpace(doc, y, lineH);
    y = flushLine(y);
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fontSize);
  return y;
}

// ─── Section detection helpers ──────────────────────────────────────────────

function isSectionHeader(line: string): boolean {
  const t = line.trim();
  if (t.length < 3) return false;
  if (t.startsWith('#')) return true;
  const alpha = t.replace(/[^a-zA-Z]/g, '');
  return alpha.length >= 3 && alpha === alpha.toUpperCase();
}

function cleanHeader(line: string): string {
  return line.trim().replace(/^#+\s*/, '');
}

function isBullet(line: string): boolean {
  const t = line.trim();
  return t.startsWith('* ') || t.startsWith('- ') || t.startsWith('• ') || /^\d+\.\s/.test(t);
}

function cleanBullet(line: string): string {
  return line.trim().replace(/^[*\-•]\s*/, '').replace(/^\d+\.\s*/, '');
}

function isPlaceholderValue(value: string): boolean {
  const lower = value.toLowerCase().trim();
  return (
    !lower ||
    lower === 'email@example.com' ||
    lower.includes('not provided') ||
    lower.includes('not specified') ||
    lower === 'n/a'
  );
}

// ─── Accent divider ─────────────────────────────────────────────────────────

function drawAccentDivider(doc: jsPDF, y: number, fullWidth = true): number {
  const pw = pageWidth(doc);
  const startX = MARGIN;
  const endX = fullWidth ? pw - MARGIN : MARGIN + contentWidth(doc) * 0.4;

  // Two-tone gradient-like divider: thick violet on left, thin light on right
  const midX = startX + (endX - startX) * 0.35;

  doc.setDrawColor(...VIOLET);
  doc.setLineWidth(0.8);
  doc.line(startX, y, midX, y);

  doc.setDrawColor(...VIOLET_LIGHT);
  doc.setLineWidth(0.3);
  doc.line(midX, y, endX, y);

  return y + 2;
}

// ─── Contact info row ───────────────────────────────────────────────────────

function renderContactRow(doc: jsPDF, contactInfo: CareerAssets['contactInfo'], y: number): number {
  const parts: string[] = [];
  if (!isPlaceholderValue(contactInfo.email)) parts.push(contactInfo.email);
  if (!isPlaceholderValue(contactInfo.phone)) parts.push(contactInfo.phone);
  if (!isPlaceholderValue(contactInfo.location)) parts.push(contactInfo.location);

  if (parts.length === 0) return y;

  const row = parts.join('  \u2022  ');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(row, MARGIN, y);

  return y + 6;
}

// ─── Skills bar ─────────────────────────────────────────────────────────────

function renderSkillsBar(doc: jsPDF, skills: string[], y: number): number {
  if (!skills.length) return y;

  const pw = pageWidth(doc);
  const barH = 8;

  y = ensureSpace(doc, y, barH + 4);

  // Background band with subtle border
  doc.setFillColor(...SKILLS_BG);
  doc.roundedRect(MARGIN, y - 2, pw - MARGIN * 2, barH, 2, 2, 'F');
  doc.setDrawColor(...VIOLET_LIGHT);
  doc.setLineWidth(0.15);
  doc.roundedRect(MARGIN, y - 2, pw - MARGIN * 2, barH, 2, 2, 'S');

  // Label
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(...VIOLET);
  doc.text('KEY SKILLS', MARGIN + 3, y + 3.5);

  // Skills text
  const labelW = doc.getTextWidth('KEY SKILLS') + 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...BODY);
  const skillsText = skills.slice(0, 12).join('  \u2022  ');
  const availableWidth = pw - MARGIN * 2 - labelW - 6;
  const truncated = doc.splitTextToSize(skillsText, availableWidth)[0] || skillsText;
  doc.text(truncated, MARGIN + 3 + labelW, y + 3.5);

  return y + barH + 4;
}

// ─── Section header renderer ────────────────────────────────────────────────

function renderSectionHeader(doc: jsPDF, text: string, y: number, sectionNumber?: number): number {
  y = ensureSpace(doc, y, 14);
  y += SECTION_GAP;

  const pw = pageWidth(doc);

  // Section number badge (if provided)
  let headerX = MARGIN;
  if (sectionNumber !== undefined) {
    const badgeText = String(sectionNumber);
    doc.setFillColor(...VIOLET);
    doc.circle(MARGIN + 3, y - 1.5, 3.5, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...WHITE);
    doc.text(badgeText, MARGIN + 3 - doc.getTextWidth(badgeText) / 2, y - 0.5);
    headerX = MARGIN + 10;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(...VIOLET);
  doc.text(text.toUpperCase(), headerX, y);
  y += 2;

  // Subtle underline
  doc.setDrawColor(...VIOLET_LIGHT);
  doc.setLineWidth(0.25);
  doc.line(headerX, y, pw - MARGIN, y);
  y += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...BODY);

  return y;
}

// ═══════════════════════════════════════════════════════════════════════════
// 1. RESUME PDF
// ═══════════════════════════════════════════════════════════════════════════

export function generateResumePDF(resumeText: string, candidateName: string, assets?: CareerAssets): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  setPDFMetadata(doc, `${candidateName} - Resume`, candidateName, ['resume', 'CV']);
  const cw = contentWidth(doc);
  let y = MARGIN;

  // ── Brand icon (small V glyph) ──
  doc.setFillColor(...VIOLET);
  doc.roundedRect(MARGIN, y - 4, 6, 6, 1, 1, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...WHITE);
  doc.text('V', MARGIN + 1.2, y + 0.2);

  // ── Header: Name ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...BODY);
  doc.text(candidateName, MARGIN + 9, y);
  y += 7;

  // ── Header: Role tagline ──
  if (assets?.role) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(...VIOLET);
    doc.text(assets.role, MARGIN + 9, y);
    y += 6;
  }

  // ── Contact info row ──
  if (assets?.contactInfo) {
    y = renderContactRow(doc, assets.contactInfo, y);
  }

  // ── Accent divider ──
  y = drawAccentDivider(doc, y);
  y += 4;

  // ── Skills bar ──
  const skills = assets?.extracted?.skills || assets?.keywords || [];
  y = renderSkillsBar(doc, skills, y);

  // ── Parse and render body ──
  const lines = resumeText.split('\n');
  let sectionNum = 0;

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();

    if (!trimmed) {
      y += 2;
      continue;
    }

    // Section Header
    if (isSectionHeader(trimmed)) {
      sectionNum++;
      y = renderSectionHeader(doc, cleanHeader(trimmed), y, sectionNum);
      continue;
    }

    // Bullet Point
    if (isBullet(trimmed)) {
      const bulletText = cleanBullet(trimmed);
      const xPos = MARGIN + BULLET_INDENT;

      y = ensureSpace(doc, y, LINE_H);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...BODY);
      doc.text('\u2022', MARGIN + 2, y);

      y = renderWrappedBoldLine(doc, bulletText, xPos, y, cw - BULLET_INDENT, 10, LINE_H, BULLET_HANG);
      continue;
    }

    // Regular body text
    doc.setTextColor(...BODY);
    y = renderWrappedBoldLine(doc, trimmed, MARGIN, y, cw, 10, LINE_H);
  }

  stampFooters(doc);
  doc.save(`${safeName(candidateName)}-Resume.pdf`);
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. COVER LETTER PDF
// ═══════════════════════════════════════════════════════════════════════════

export function generateCoverLetterPDF(coverLetterText: string, candidateName: string, assets?: CareerAssets): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  setPDFMetadata(doc, `${candidateName} - Cover Letter`, candidateName, ['cover letter', 'job application']);
  const pw = pageWidth(doc);
  const cw = contentWidth(doc);
  let y = MARGIN;

  // ── Brand icon ──
  doc.setFillColor(...VIOLET);
  doc.roundedRect(MARGIN, y - 4, 6, 6, 1, 1, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...WHITE);
  doc.text('V', MARGIN + 1.2, y + 0.2);

  // ── Letterhead: Name ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...BODY);
  doc.text(candidateName, MARGIN + 9, y);
  y += 5;

  // ── Contact info ──
  if (assets?.contactInfo) {
    y = renderContactRow(doc, assets.contactInfo, y);
  }

  // ── Date (right-aligned) ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...MUTED);
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const dateWidth = doc.getTextWidth(dateStr);
  doc.text(dateStr, pw - MARGIN - dateWidth, y);
  y += 4;

  // ── Accent divider ──
  y = drawAccentDivider(doc, y);
  y += 10;

  // ── Smart salutation ──
  const paragraphs = coverLetterText.split('\n');
  let bodyStartIndex = 0;

  const firstLine = paragraphs[0]?.trim() || '';
  if (/^dear\s/i.test(firstLine) || /^to\s/i.test(firstLine) || /^hello/i.test(firstLine)) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(...BODY);
    doc.text(firstLine, MARGIN, y);
    y += 10;
    bodyStartIndex = 1;
  } else {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(...BODY);
    doc.text('Dear Hiring Manager,', MARGIN, y);
    y += 10;
  }

  // ── Body paragraphs ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...BODY);

  let prevWasBlank = false;

  for (let i = bodyStartIndex; i < paragraphs.length; i++) {
    const trimmed = paragraphs[i].trim();

    if (!trimmed) {
      if (!prevWasBlank) y += PARA_GAP;
      prevWasBlank = true;
      continue;
    }
    prevWasBlank = false;

    // Detect closing lines
    if (/^(sincerely|best regards|warm regards|kind regards|regards|yours|respectfully)/i.test(trimmed)) {
      y += 6;
      y = ensureSpace(doc, y, LINE_H * 3);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(10);
      doc.setTextColor(...BODY);
      doc.text(trimmed, MARGIN, y);
      y += LINE_H;

      for (let j = i + 1; j < paragraphs.length; j++) {
        const nextTrimmed = paragraphs[j].trim();
        if (!nextTrimmed) continue;
        y += 4;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text(nextTrimmed, MARGIN, y);
        y += LINE_H;
        i = j;
        break;
      }
      doc.setFont('helvetica', 'normal');
      continue;
    }

    doc.setTextColor(...BODY);
    y = renderWrappedBoldLine(doc, trimmed, MARGIN, y, cw, 10, LINE_H);
    y += 2;
  }

  stampFooters(doc);
  doc.save(`${safeName(candidateName)}-CoverLetter.pdf`);
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. LINKEDIN BIO PDF
// ═══════════════════════════════════════════════════════════════════════════

export function generateLinkedInBioPDF(bioText: string, candidateName: string, _assets?: CareerAssets): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  setPDFMetadata(doc, `${candidateName} - LinkedIn Bio`, candidateName, ['LinkedIn', 'professional bio']);
  const pw = pageWidth(doc);
  const cw = contentWidth(doc);
  let y = MARGIN;

  // ── Brand icon ──
  doc.setFillColor(...VIOLET);
  doc.roundedRect(MARGIN, y - 4, 6, 6, 1, 1, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...WHITE);
  doc.text('V', MARGIN + 1.2, y + 0.2);

  // ── Title ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...VIOLET);
  doc.text('LinkedIn About Section', MARGIN + 9, y);
  y += 8;

  // ── Subtitle ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text(`Prepared for ${candidateName}`, MARGIN, y);
  y += 6;

  // ── Accent divider ──
  y = drawAccentDivider(doc, y);
  y += 10;

  // ── Copy-hint ──
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text('Copy the text below and paste it into your LinkedIn About section.', MARGIN, y);
  y += 8;

  // ── Body ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(...BODY);

  const paragraphs = bioText.split('\n');
  for (const para of paragraphs) {
    const trimmed = para.trim();
    if (!trimmed) {
      y += PARA_GAP;
      continue;
    }

    y = renderWrappedBoldLine(doc, trimmed, MARGIN, y, cw, 10.5, LINE_H);
    y += 2;
  }

  // ── Character count badge (accurate - strips markdown) ──
  y += 10;
  y = ensureSpace(doc, y, 12);

  const visibleText = stripMarkdown(bioText);
  const charCount = visibleText.length;
  const charLimit = 2600;
  const badgeText = `${charCount.toLocaleString()} / ${charLimit.toLocaleString()} characters`;
  const isOverLimit = charCount > charLimit;

  const badgeW = doc.getTextWidth(badgeText) + 14;
  const badgeH = 7;
  const badgeX = MARGIN;

  doc.setFillColor(...(isOverLimit ? [255, 235, 235] as [number, number, number] : SKILLS_BG));
  doc.roundedRect(badgeX, y - 4.5, badgeW, badgeH, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(...(isOverLimit ? ERROR_CLR : VIOLET));
  doc.text(badgeText, badgeX + 7, y);

  // Status indicator dot
  doc.setFillColor(...(isOverLimit ? ERROR_CLR : SUCCESS_CLR));
  doc.circle(badgeX + 3, y - 1, 1.2, 'F');

  stampFooters(doc);
  doc.save(`${safeName(candidateName)}-LinkedInBio.pdf`);
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. INTERVIEW PREP PDF
// ═══════════════════════════════════════════════════════════════════════════

export function generateInterviewPrepPDF(prepText: string, candidateName: string, assets?: CareerAssets): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  setPDFMetadata(doc, `${candidateName} - Interview Prep`, candidateName, ['interview', 'preparation', 'questions']);
  const pw = pageWidth(doc);
  const cw = contentWidth(doc);
  let y = MARGIN;

  // ── Brand icon ──
  doc.setFillColor(...VIOLET);
  doc.roundedRect(MARGIN, y - 4, 6, 6, 1, 1, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...WHITE);
  doc.text('V', MARGIN + 1.2, y + 0.2);

  // ── Title block ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...VIOLET);
  doc.text('Interview Preparation Guide', MARGIN + 9, y);
  y += 8;

  // ── Subtitle ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  const role = assets?.role || 'Professional Candidate';
  doc.text(`Strategic guide for ${candidateName} \u2022 ${role}`, MARGIN, y);
  y += 6;

  // ── Accent divider ──
  y = drawAccentDivider(doc, y);
  y += 8;

  // ── Parse content with structure detection ──
  const lines = prepText.split('\n');
  let sectionNumber = 0;

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();

    if (!trimmed) {
      y += 2.5;
      continue;
    }

    // Section header
    if (isSectionHeader(trimmed)) {
      sectionNumber++;
      const headerText = cleanHeader(trimmed);

      y = ensureSpace(doc, y, 16);
      y += SECTION_GAP;

      // Section number badge
      const badgeText = String(sectionNumber);
      doc.setFillColor(...VIOLET);
      doc.circle(MARGIN + 3, y - 1.5, 3.5, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...WHITE);
      doc.text(badgeText, MARGIN + 3 - doc.getTextWidth(badgeText) / 2, y - 0.5);

      // Header text
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(...VIOLET);
      doc.text(headerText, MARGIN + 10, y);
      y += 3;

      // Underline
      doc.setDrawColor(...VIOLET_LIGHT);
      doc.setLineWidth(0.2);
      doc.line(MARGIN + 10, y, pw - MARGIN, y);
      y += 5;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...BODY);
      continue;
    }

    // Q&A formatting
    if (/^(Q:|Question:|Q\d|"\*\*Q)/i.test(trimmed) || /^\*\*Q/i.test(trimmed)) {
      y = ensureSpace(doc, y, LINE_H * 2);
      y += 2;
      const questionText = trimmed.replace(/^(Q:|Question:)\s*/i, '').trim();
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...BODY);
      y = renderWrappedBoldLine(doc, questionText, MARGIN, y, cw, 10, LINE_H);
      y += 1;
      continue;
    }

    if (/^(A:|Answer:|Sample Answer:)/i.test(trimmed)) {
      const answerText = trimmed.replace(/^(A:|Answer:|Sample Answer:)\s*/i, '').trim();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...BODY);
      y = renderWrappedBoldLine(doc, answerText, MARGIN + 3, y, cw - 3, 10, LINE_H);
      y += 2;
      continue;
    }

    // Tip boxes (improved height calculation)
    if (/^(💡|Tip:|Pro Tip:|Note:)/i.test(trimmed)) {
      const tipText = trimmed.replace(/^(💡|Tip:|Pro Tip:|Note:)\s*/i, '').trim();

      doc.setFontSize(9);
      const tipLines: string[] = doc.splitTextToSize(tipText, cw - 16);
      const tipContentH = tipLines.length * 4.5;
      const tipH = Math.max(10, tipContentH + 8); // accurate: content + padding

      y = ensureSpace(doc, y, tipH + 4);

      // Background strip
      doc.setFillColor(...TIP_BG);
      doc.roundedRect(MARGIN, y - 2, pw - MARGIN * 2, tipH, 2, 2, 'F');

      // Left accent bar
      doc.setFillColor(...VIOLET);
      doc.roundedRect(MARGIN, y - 2, 1.5, tipH, 0.5, 0.5, 'F');

      // Tip label
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(...VIOLET);
      doc.text('TIP', MARGIN + 5, y + 2);

      // Tip text
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...BODY);
      let tipY = y + 2;
      for (const tl of tipLines) {
        doc.text(tl, MARGIN + 5, tipY);
        tipY += 4.5;
      }

      y += tipH + 3;
      continue;
    }

    // Bullet Point
    if (isBullet(trimmed)) {
      const bulletText = cleanBullet(trimmed);
      const xPos = MARGIN + BULLET_INDENT;

      y = ensureSpace(doc, y, LINE_H);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...BODY);
      doc.text('\u2022', MARGIN + 2, y);

      y = renderWrappedBoldLine(doc, bulletText, xPos, y, cw - BULLET_INDENT, 10, LINE_H, BULLET_HANG);
      continue;
    }

    // Regular text
    doc.setTextColor(...BODY);
    y = renderWrappedBoldLine(doc, trimmed, MARGIN, y, cw, 10, LINE_H);
  }

  stampFooters(doc);
  doc.save(`${safeName(candidateName)}-Interview-Prep.pdf`);
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. PLAIN TEXT DOWNLOAD (unchanged)
// ═══════════════════════════════════════════════════════════════════════════

export function downloadAsText(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename.endsWith('.txt') ? filename : `${filename}.txt`;
  anchor.style.display = 'none';

  document.body.appendChild(anchor);
  anchor.click();

  // Cleanup — schedule revocation so the browser has time to initiate the download
  requestAnimationFrame(() => {
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  });
}
