import jsPDF from 'jspdf';

// ─── Constants ──────────────────────────────────────────────────────────────
const MARGIN = 20;
const ACCENT_RGB: [number, number, number] = [124, 58, 237];
const BODY_RGB: [number, number, number] = [26, 26, 46];
const MUTED_RGB: [number, number, number] = [100, 100, 100];
const FOOTER_RGB: [number, number, number] = [150, 150, 150];
const LINE_HEIGHT = 5;
const SECTION_GAP = 5;
const BULLET_INDENT = 5;

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Safe filename from candidate name. */
function safeName(name: string): string {
  return name.replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');
}

/** True when a trimmed line looks like a section header (ALL CAPS ≥ 3 chars, or starts with #). */
function isSectionHeader(line: string): boolean {
  const t = line.trim();
  if (t.length < 3) return false;
  if (t.startsWith('#')) return true;
  // All caps (ignoring non-alpha characters like colons, dashes)
  const alpha = t.replace(/[^a-zA-Z]/g, '');
  return alpha.length >= 3 && alpha === alpha.toUpperCase();
}

/** Strip leading # symbols from markdown headers. */
function cleanHeader(line: string): string {
  return line.trim().replace(/^#+\s*/, '');
}

/** True when a line is a bullet point (* or - prefix). */
function isBullet(line: string): boolean {
  const t = line.trim();
  return t.startsWith('* ') || t.startsWith('- ') || t.startsWith('• ');
}

/** Strip bullet prefix and return clean text. */
function cleanBullet(line: string): string {
  return line.trim().replace(/^[*\-•]\s*/, '');
}

/** Stamp "Generated by VoiceCV • voicecv.app" footer on every page. */
function stampFooters(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  const footerText = 'Generated by VoiceCV \u2022 voicecv.app';

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...FOOTER_RGB);

    const textWidth = doc.getTextWidth(footerText);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    doc.text(footerText, (pageWidth - textWidth) / 2, pageHeight - 10);
  }
}

/** Check if cursor would overflow the printable area, and add a page if so. */
function ensureSpace(doc: jsPDF, cursorY: number, needed: number): number {
  const maxY = doc.internal.pageSize.getHeight() - MARGIN - 15; // leave room for footer
  if (cursorY + needed > maxY) {
    doc.addPage();
    return MARGIN;
  }
  return cursorY;
}

// ─── 1. Resume PDF ──────────────────────────────────────────────────────────

export function generateResumePDF(resumeText: string, candidateName: string): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - MARGIN * 2;
  let y = MARGIN;

  // ── Candidate Name ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...BODY_RGB);
  doc.text(candidateName, MARGIN, y);
  y += 8;

  // ── Thin violet horizontal rule ──
  doc.setDrawColor(...ACCENT_RGB);
  doc.setLineWidth(0.35);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 10;

  // ── Parse and render lines ──
  const lines = resumeText.split('\n');

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();

    // Blank line → small vertical gap
    if (!trimmed) {
      y += 2;
      continue;
    }

    // ── Section Header ──
    if (isSectionHeader(trimmed)) {
      const headerText = cleanHeader(trimmed);
      y = ensureSpace(doc, y, 12);

      y += SECTION_GAP;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(...ACCENT_RGB);
      doc.text(headerText, MARGIN, y);
      y += 6;

      // Reset to body style
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...BODY_RGB);
      continue;
    }

    // ── Bullet Point ──
    if (isBullet(trimmed)) {
      const bulletText = '\u2022  ' + cleanBullet(trimmed);
      const xPos = MARGIN + BULLET_INDENT;
      const wrappedLines: string[] = doc.splitTextToSize(bulletText, contentWidth - BULLET_INDENT);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...BODY_RGB);

      for (const segment of wrappedLines) {
        y = ensureSpace(doc, y, LINE_HEIGHT);
        doc.text(segment, xPos, y);
        y += LINE_HEIGHT;
      }
      continue;
    }

    // ── Regular Body Text ──
    const wrappedLines: string[] = doc.splitTextToSize(trimmed, contentWidth);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...BODY_RGB);

    for (const segment of wrappedLines) {
      y = ensureSpace(doc, y, LINE_HEIGHT);
      doc.text(segment, MARGIN, y);
      y += LINE_HEIGHT;
    }
  }

  stampFooters(doc);
  doc.save(`${safeName(candidateName)}-Resume.pdf`);
}

// ─── 2. Cover Letter PDF ────────────────────────────────────────────────────

export function generateCoverLetterPDF(coverLetterText: string, candidateName: string): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - MARGIN * 2;
  let y = MARGIN;

  // ── Candidate Name (top-left) ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...BODY_RGB);
  doc.text(candidateName, MARGIN, y);

  // ── Date (top-right) ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED_RGB);
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const dateWidth = doc.getTextWidth(dateStr);
  doc.text(dateStr, pageWidth - MARGIN - dateWidth, y);
  y += 6;

  // ── Thin violet rule ──
  doc.setDrawColor(...ACCENT_RGB);
  doc.setLineWidth(0.35);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 14;

  // ── Salutation ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...BODY_RGB);
  doc.text('Dear Hiring Manager,', MARGIN, y);
  y += 10;

  // ── Body ──
  const paragraphs = coverLetterText.split('\n');

  for (const para of paragraphs) {
    const trimmed = para.trim();
    if (!trimmed) {
      y += 4;
      continue;
    }

    const wrappedLines: string[] = doc.splitTextToSize(trimmed, contentWidth);

    for (const segment of wrappedLines) {
      y = ensureSpace(doc, y, LINE_HEIGHT);
      doc.text(segment, MARGIN, y);
      y += LINE_HEIGHT;
    }
    y += 2; // paragraph spacing
  }

  stampFooters(doc);
  doc.save(`${safeName(candidateName)}-CoverLetter.pdf`);
}

// ─── 3. LinkedIn Bio PDF ────────────────────────────────────────────────────

export function generateLinkedInBioPDF(bioText: string, candidateName: string): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - MARGIN * 2;
  let y = MARGIN;

  // ── Header ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...ACCENT_RGB);
  doc.text('LinkedIn About Section', MARGIN, y);
  y += 8;

  // ── Subheader ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(...MUTED_RGB);
  doc.text(`For ${candidateName}`, MARGIN, y);
  y += 6;

  // ── Thin violet rule ──
  doc.setDrawColor(...ACCENT_RGB);
  doc.setLineWidth(0.35);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 12;

  // ── Body ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...BODY_RGB);

  const wrappedLines: string[] = doc.splitTextToSize(bioText, contentWidth);

  for (const segment of wrappedLines) {
    y = ensureSpace(doc, y, LINE_HEIGHT);
    doc.text(segment, MARGIN, y);
    y += LINE_HEIGHT;
  }

  // ── Character count ──
  y += 12;
  y = ensureSpace(doc, y, LINE_HEIGHT);
  doc.setFontSize(8);
  doc.setTextColor(...MUTED_RGB);
  doc.text(`Character count: ${bioText.length}`, MARGIN, y);

  stampFooters(doc);
  doc.save(`${safeName(candidateName)}-LinkedInBio.pdf`);
}

// ─── 4. Interview Prep PDF ──────────────────────────────────────────────────

export function generateInterviewPrepPDF(prepText: string, candidateName: string): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - MARGIN * 2;
  let y = MARGIN;

  // ── Header ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...ACCENT_RGB);
  doc.text('Interview Preparation Guide', MARGIN, y);
  y += 8;

  // ── Subheader ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...MUTED_RGB);
  doc.text(`Strategic guide for ${candidateName}`, MARGIN, y);
  y += 6;

  // ── Thin violet rule ──
  doc.setDrawColor(...ACCENT_RGB);
  doc.setLineWidth(0.35);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 12;

  // ── Body ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...BODY_RGB);

  const wrappedLines: string[] = doc.splitTextToSize(prepText, contentWidth);

  for (const segment of wrappedLines) {
    y = ensureSpace(doc, y, LINE_HEIGHT);
    doc.text(segment, MARGIN, y);
    y += LINE_HEIGHT;
  }

  stampFooters(doc);
  doc.save(`${safeName(candidateName)}-Interview-Prep.pdf`);
}

// ─── 5. Plain-text download ─────────────────────────────────────────────────

export function downloadAsText(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename.endsWith('.txt') ? filename : `${filename}.txt`;
  anchor.style.display = 'none';

  document.body.appendChild(anchor);
  anchor.click();

  // Cleanup — schedule revocation so the browser has time to initiate the download
  requestAnimationFrame(() => {
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  });
}
