import React, { useState } from 'react';
import { motion } from 'motion/react';
import { useParams, Link } from 'react-router-dom';
import { 
  User, Briefcase, Mail, Linkedin, MapPin, 
  Download, Share2, ExternalLink, Award,
  CheckCircle2, Sparkles, ChevronRight, Globe,
  Code, Palette, Sun, Moon
} from 'lucide-react';
import Markdown from 'react-markdown';
import { useVoiceCVStore } from '../store/useVoiceCVStore';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { GlassPanel } from '../components/ui/GlassPanel';

type PortfolioTheme = 'dark' | 'light' | 'gradient';

const PORTFOLIO_THEMES: Array<{ id: PortfolioTheme; name: string; colors: string[] }> = [
  { id: 'dark', name: 'Midnight', colors: ['#101522', '#7C3AED', '#F59E0B'] },
  { id: 'light', name: 'Clean', colors: ['#F7F3EA', '#2857D8', '#C66A13'] },
  { id: 'gradient', name: 'Aurora', colors: ['#0D0B1F', '#7C3AED', '#10B981'] },
];

export default function PortfolioPage() {
  const { id } = useParams();
  const { assets } = useVoiceCVStore();
  const [activeTab, setActiveTab] = useState<'resume' | 'coverLetter' | 'linkedin'>('resume');
  const [portfolioTheme, setPortfolioTheme] = useState<PortfolioTheme>('dark');
  const [showThemePicker, setShowThemePicker] = useState(false);

  if (!assets) {
    return (
      <div className="flex flex-col items-center justify-center py-40 text-center space-y-6">
        <h2 className="text-3xl font-display font-bold">Portfolio Not Found</h2>
        <p className="text-[var(--muted)] max-w-md">We couldn't find the requested digital career profile. It might have expired or hasn't been generated yet.</p>
        <Link to="/">
          <Button>Create Your Profile</Button>
        </Link>
      </div>
    );
  }

  const { name = 'Professional Candidate', role, resume, coverLetter, linkedinBio, contactInfo, resumeScore } = assets;

  const handleExportHTML = () => {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${name} - Portfolio</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; background: ${portfolioTheme === 'light' ? '#F7F3EA' : '#101522'}; color: ${portfolioTheme === 'light' ? '#172033' : '#F8FAFC'}; line-height: 1.6; }
    .container { max-width: 900px; margin: 0 auto; padding: 3rem 2rem; }
    h1 { font-size: 2.5rem; font-weight: 800; margin-bottom: 0.5rem; }
    h2 { font-size: 1.5rem; font-weight: 700; margin: 2rem 0 1rem; color: #7C3AED; }
    h3 { font-size: 1.2rem; font-weight: 600; margin: 1.5rem 0 0.5rem; }
    .role { font-size: 1.2rem; color: #7C3AED; font-weight: 600; margin-bottom: 2rem; }
    .section { background: ${portfolioTheme === 'light' ? 'rgba(255,255,255,0.7)' : 'rgba(255,255,255,0.05)'}; border-radius: 1rem; padding: 2rem; margin-bottom: 1.5rem; border: 1px solid ${portfolioTheme === 'light' ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.1)'}; }
    .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; margin: 0.25rem; background: rgba(124,58,237,0.1); color: #7C3AED; border: 1px solid rgba(124,58,237,0.2); }
    .contact { display: flex; gap: 1.5rem; flex-wrap: wrap; margin-top: 1rem; }
    .contact a { color: #7C3AED; text-decoration: none; }
    .contact a:hover { text-decoration: underline; }
    pre { white-space: pre-wrap; font-family: inherit; }
    @media (max-width: 640px) { .container { padding: 1.5rem 1rem; } h1 { font-size: 1.8rem; } }
  </style>
</head>
<body>
  <div class="container">
    <h1>${name}</h1>
    <p class="role">${role}</p>
    <div class="contact">
      ${contactInfo?.email ? `<a href="mailto:${contactInfo.email}">${contactInfo.email}</a>` : ''}
      ${contactInfo?.location ? `<span>${contactInfo.location}</span>` : ''}
    </div>
    <div class="section"><h2>Resume</h2><pre>${resume}</pre></div>
    <div class="section"><h2>Cover Letter</h2><pre>${coverLetter}</pre></div>
    <div class="section"><h2>LinkedIn Bio</h2><pre>${linkedinBio}</pre></div>
    <div style="text-align:center;margin-top:3rem;color:${portfolioTheme === 'light' ? '#687386' : '#64748B'};font-size:0.75rem;">Generated by VoiceCV</div>
  </div>
</body>
</html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${name.replace(/\s+/g, '_')}_Portfolio.html`;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  };

  const handleExportMarkdown = () => {
    const md = `# ${name}\n\n**${role}**\n\n${contactInfo?.email ? `Email: ${contactInfo.email}` : ''}\n${contactInfo?.location ? `Location: ${contactInfo.location}` : ''}\n\n---\n\n## Resume\n\n${resume}\n\n---\n\n## Cover Letter\n\n${coverLetter}\n\n---\n\n## LinkedIn Bio\n\n${linkedinBio}`;
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${name.replace(/\s+/g, '_')}_Portfolio.md`;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({ title: `${name} - Portfolio`, text: `Check out ${name}'s professional portfolio`, url: window.location.href });
      } catch {}
    } else {
      navigator.clipboard.writeText(window.location.href);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="relative mb-12">
        <div className="absolute -top-24 -left-24 w-96 h-96 bg-[var(--accent)]/20 blur-[120px] rounded-full pointer-events-none" />
        <div className="absolute top-0 right-0 w-64 h-64 bg-[var(--warm)]/10 blur-[100px] rounded-full pointer-events-none" />

        <div className="flex flex-col md:flex-row gap-8 items-start md:items-end justify-between relative z-10">
          <div className="flex items-center gap-6">
            <div className="w-24 h-24 rounded-3xl bg-gradient-to-br from-[var(--accent)] to-[var(--bg)] flex items-center justify-center border border-[var(--border)] shadow-2xl relative overflow-hidden group">
              <User size={48} className="text-[var(--text)] relative z-10" />
            </div>
            <div>
              <div className="flex items-center gap-3 mb-1">
                <h1 className="text-4xl md:text-5xl font-display font-black tracking-tight text-[var(--text)]">{name}</h1>
                <CheckCircle2 size={24} className="text-green-400" />
              </div>
              <p className="text-xl text-[var(--accent)] font-bold flex items-center gap-2">
                <Briefcase size={18} />
                {role}
              </p>
              {resumeScore && (
                <div className="flex flex-wrap gap-4 mt-4">
                  <Badge variant="outline" className="bg-[var(--surface)] border-[var(--border)] py-1.5 px-3 text-[var(--text)]">
                    <Award size={12} className="mr-1.5" /> Score: {resumeScore.overall}/100
                  </Badge>
                  {contactInfo?.location && (
                    <Badge variant="outline" className="bg-[var(--surface)] border-[var(--border)] py-1.5 px-3 text-[var(--text)]">
                      <MapPin size={12} className="mr-1.5" /> {contactInfo.location}
                    </Badge>
                  )}
                </div>
              )}
            </div>
          </div>

          <div className="flex flex-wrap gap-3">
            <Button variant="secondary" onClick={handleShare} leftIcon={<Share2 size={16} />}>Share</Button>
            <div className="relative">
              <Button variant="secondary" onClick={() => setShowThemePicker(!showThemePicker)} leftIcon={<Palette size={16} />}>Theme</Button>
              {showThemePicker && (
                <div className="absolute right-0 top-full mt-2 p-3 rounded-2xl border border-[var(--border)] bg-[var(--bg)] shadow-xl z-10 space-y-2">
                  {PORTFOLIO_THEMES.map((t) => (
                    <button key={t.id} onClick={() => { setPortfolioTheme(t.id); setShowThemePicker(false); }}
                      className={`flex items-center gap-3 w-full px-3 py-2 rounded-xl text-sm font-bold transition-all ${portfolioTheme === t.id ? 'bg-[var(--accent)] text-[var(--on-accent)]' : 'text-[var(--muted)] hover:bg-[var(--surface)]'}`}>
                      <div className="flex gap-1">{t.colors.map((c) => <div key={c} className="w-3 h-3 rounded-full border border-[var(--border)]" style={{ backgroundColor: c }} />)}</div>
                      {t.name}
                    </button>
                  ))}
                </div>
              )}
            </div>
            <Button onClick={handleExportHTML} leftIcon={<Globe size={16} />}>Export HTML</Button>
            <Button onClick={handleExportMarkdown} leftIcon={<Download size={16} />}>Export MD</Button>
          </div>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className="lg:col-span-4 space-y-6">
          <GlassPanel className="p-8 space-y-6">
            <h3 className="text-lg font-display font-bold flex items-center gap-2 text-[var(--text)]">
              <Sparkles size={18} className="text-[var(--warm)]" />
              AI-Optimized Context
            </h3>
            <p className="text-sm text-[var(--muted)] leading-relaxed">
              This profile was generated using Gemini from a single voice session, optimized for maximum impact.
            </p>
            <div className="space-y-4">
              {resumeScore && (
                <>
                  <div className="flex items-center justify-between p-3 rounded-xl bg-[var(--surface)] border border-[var(--border)]">
                    <span className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">ATS Score</span>
                    <span className="text-lg font-display font-bold text-green-400">{resumeScore.atsKeywords}/100</span>
                  </div>
                  <div className="flex items-center justify-between p-3 rounded-xl bg-[var(--surface)] border border-[var(--border)]">
                    <span className="text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Impact</span>
                    <span className="text-lg font-display font-bold text-[var(--accent)]">{resumeScore.impact}/100</span>
                  </div>
                </>
              )}
            </div>
          </GlassPanel>

          <Card variant="solid" className="p-8 space-y-6">
            <h3 className="text-lg font-display font-bold text-[var(--text)]">Contact & Links</h3>
            <div className="space-y-4">
              {contactInfo?.email && (
                <a href={`mailto:${contactInfo.email}`} className="flex items-center gap-3 p-3 rounded-xl bg-[var(--surface)] border border-[var(--border)] hover:border-[var(--accent)]/30 transition-all group">
                  <div className="w-10 h-10 rounded-lg bg-green-500/10 flex items-center justify-center text-green-500">
                    <Mail size={18} />
                  </div>
                  <div>
                    <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted)]">Email</p>
                    <p className="text-sm font-medium text-[var(--text)]">{contactInfo.email}</p>
                  </div>
                </a>
              )}
              <div className="flex items-center gap-3 p-3 rounded-xl bg-[var(--surface)] border border-[var(--border)]">
                <div className="w-10 h-10 rounded-lg bg-blue-500/10 flex items-center justify-center text-blue-500">
                  <Linkedin size={18} />
                </div>
                <div>
                  <p className="text-[10px] font-bold uppercase tracking-widest text-[var(--muted)]">LinkedIn</p>
                  <p className="text-sm font-medium text-[var(--text)]">Professional Profile</p>
                </div>
              </div>
            </div>
          </Card>
        </motion.div>

        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.3 }} className="lg:col-span-8">
          <div className="mb-8 flex gap-2 p-1 bg-[var(--surface)] border border-[var(--border)] rounded-2xl w-fit">
            {(['resume', 'coverLetter', 'linkedin'] as const).map((tab) => (
              <button key={tab} onClick={() => setActiveTab(tab)}
                className={`px-6 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${
                  activeTab === tab ? 'bg-[var(--accent)] text-[var(--on-accent)] shadow-lg' : 'text-[var(--muted)] hover:text-[var(--text)]'
                }`}>
                {tab.replace(/([A-Z])/, ' $1')}
              </button>
            ))}
          </div>

          <Card padding="none" className="overflow-hidden">
            <div className="p-8 bg-[var(--surface)] border-b border-[var(--border)] flex items-center justify-between">
              <h4 className="text-lg font-display font-extrabold flex items-center gap-3 text-[var(--text)]">
                <div className="w-8 h-8 rounded-lg bg-[var(--accent-soft)] flex items-center justify-center text-[var(--accent)]">
                  {activeTab === 'resume' ? <Briefcase size={16} /> : activeTab === 'coverLetter' ? <Mail size={16} /> : <Linkedin size={16} />}
                </div>
                {activeTab.charAt(0).toUpperCase() + activeTab.slice(1).replace(/([A-Z])/, ' $1')}
              </h4>
            </div>
            
            <div className="h-[600px] overflow-y-auto p-6 sm:p-10 custom-scrollbar">
              <article className="markdown-body max-w-none text-[var(--text)]">
                <Markdown>{activeTab === 'resume' ? resume : activeTab === 'coverLetter' ? coverLetter : linkedinBio}</Markdown>
              </article>
            </div>

            <div className="p-6 bg-[var(--surface)] border-t border-[var(--border)] flex justify-end">
              <Link to="/interview">
                <Button variant="ghost" className="text-[var(--warm)]">
                  Practice Interview <ChevronRight size={16} className="ml-2" />
                </Button>
              </Link>
            </div>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}
